webapp/word/models.py
from webapp.db import db


class Cards(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer)
    original_word = db.Column(db.String(30))
    translatted_word = db.Column(db.String(140))

    def __repr__(self):
        return f"{self.original_word}: {self.translatted_word}: id={self.id}"

webapp/word/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class WordForm(FlaskForm):
    submit = SubmitField('Перевести', render_kw={"class": "btn btn-primary"})
    word_for_translate = StringField('Введите слово для перевода', validators=[DataRequired()], render_kw={"class": "form-control"})
    transleted_word = StringField('Перевод', render_kw={"class": "form-control"})
    add = SubmitField('Добавить', render_kw={"class": "btn btn-primary"})
    edit = SubmitField('Редактировать', render_kw={"class": "btn btn-primary"})
    delete = SubmitField('Удалить', render_kw={"class": "btn btn-primary"})

webapp/word/views.py
from flask import Blueprint, request, redirect, render_template, flash, url_for
from flask_login import current_user

from get_translated_word import get_translation
from webapp.db import db
from webapp.word.models import Cards
from webapp.word.forms import WordForm


blueprint = Blueprint('word', __name__)


@blueprint.route('/')
@blueprint.route('/index')
def index():
    title = "Домашная страница"
    return render_template('word/index.html', page_title=title)

@blueprint.route('/my_dictionary')
def my_dictionary():
    title = "Мой словарь"
    cards_db = Cards.query.filter(Cards.user_id==current_user.get_id()).all()
    word_form = WordForm()
    if current_user.is_authenticated:
        return render_template('word/my_dictionary.html', page_title=title, cards=cards_db, form=word_form)
    else:
        flash('вы не вошли на сайт')
        return redirect(url_for('user.login'))

@blueprint.route('/add_word', methods=["POST"])
def add_word():
    form = WordForm()
    user_id = current_user.get_id()
    if form.add.data:
        word_exist_in_db = Cards.query.filter(Cards.original_word==form.word_for_translate.data, Cards.user_id==user_id).count()
        if not word_exist_in_db:
            if form.validate_on_submit():
                translation = get_translation(form.word_for_translate.data)
                if translation:
                    new_word = Cards(original_word=form.word_for_translate.data, translatted_word=translation, user_id=user_id)
                    db.session.add(new_word)
                    db.session.commit()
                    flash('Вы успешно добавили слово!')
                else:
                    flash('Не найден перевод')
        else:
            flash('Слово уже в вашем словаре')
        return redirect(url_for('word.my_dictionary'))
    elif form.submit.data:
        translation = get_translation(form.word_for_translate.data)
        if translation:
            trnlated_word = translation
            flash(form.word_for_translate.data)
            flash(trnlated_word)
        else:
            flash('Не найден перевод')
        return redirect(url_for('word.my_dictionary'))

@blueprint.route('/delete_word/<int:word_id>')
def delete_word(word_id):
    user_id = current_user.get_id()
    word_to_del = Cards.query.filter(Cards.id==word_id, Cards.user_id==user_id).first()
    db.session.delete(word_to_del)
    db.session.commit()
    flash ("Вы успешно удалили слово")
    return redirect(url_for('word.my_dictionary')) 

@blueprint.route('/word_edit/<int:word_id>', methods=['POST', 'GET'])
def word_edit(word_id):
    word = Cards.query.filter(Cards.id==word_id).first()
    form = WordForm()
    if request.method == 'GET':
        return render_template('word/word_edit.html', form=form, cards=word)
    else:
        if form.validate_on_submit():
            word.original_word = form.word_for_translate.data 
            word.translatted_word = form.transleted_word.data
            db.session.commit()
            return redirect(url_for('word.my_dictionary'))

        else:
            return redirect(url_for('word.my_dictionary'))

webapp/templates/word/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-4">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}<br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %} 
    </div>
    <div class="col-8">

    </div>
</div>
{% endblock %}

webapp/templates/word/my_dictionary.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-4">
        <form action="{{ url_for('word.add_word') }}" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.word_for_translate.label }}
                {{ form.word_for_translate }}
            </div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
        <div class="form-group">
            {{ form.submit() }} {{ form.add() }}
        </div>
        </form>
            {% for card in cards %}
            <div class="card">
                <div class="card-body">
                    <div><p>{{ card.original_word }} {{ card.translatted_word }}</p></div>
                    <a class="btn btn-primary" href="{{ url_for('word.word_edit', word_id=card.id) }}">редактировать</span></a>
                    <a class="btn btn-primary" href="{{ url_for('word.delete_word', word_id=card.id) }}">удалить</span></a>
                </div>
            </div>
            {% endfor %}
    </div>
    <div class="col-8">

    </div>
</div>
{% endblock %}

webapp/templates/word/word_edit.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <form action="" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    Слово
                    {{ form.word_for_translate  }} 
                </div>
                <div class="form-group">
                    Перевод
                    {{ form.transleted_word }}
                </div>
                {{ form.edit() }}
            </form>
        </div>
        <div class="col-8">
            
        </div>
    </div>
{% endblock %}