webapp/user/views.py
from flask import Blueprint, request, redirect, render_template, flash, url_for
from flask_login import current_user, login_user, logout_user

from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.db import db

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        print('1')
        return redirect(url_for('word.index'))
    form = LoginForm()
    title = 'Авторизация'
    return render_template('user/login.html', page_title=title, form=form)

@blueprint.route('/process_login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('вы успешно вошли на сайт')
            return redirect(url_for('word.index'))

    flash('неправильный имя или пароль')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогины')
    return redirect(url_for('word.index'))



@blueprint.route('/registration')
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('word.index')) 
    else:
        form_reg = RegistrationForm()
        title = "Регистрация"
        return render_template('user/registration.html', page_title=title, form=form_reg)

@blueprint.route('/process_reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data)
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('word.index'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле {}: - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.registration'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include 'menu.html' %}
    <div class="container">
        <h1>{{ page_title }}</h1>
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-4">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}<br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %} 
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.word_for_translate.label }}
                {{ form.word_for_translate }}
            </div>
            {{ form.submit() }}
        </form>
        {% for card in cards %}
        <div><p>{{ card }}</p></div>
        {% endfor %}
    </div>
    <div class="col-8">

    </div>
</div>
{% endblock %}

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Переводчик</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Главная страница </span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('word.my_dictionary') }}">Мой словарь </span></a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
      </form>
      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link">Привет, {{current_user.username}}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.registration') }}">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

webapp/templates/my_dictionary.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-4">
        <form action="{{ url_for('add_word') }}" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.word_for_translate.label }}
                {{ form.word_for_translate }}
            </div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
        <div class="form-group">
            {{ form.submit() }} {{ form.add() }}
        </div>
        </form>
            {% for card in cards %}
            <div class="card">
                <div class="card-body">
                    <div><p>{{ card.original_word }} {{ card.translatted_word }}</p></div>
                    <a class="btn btn-primary" href="{{ url_for('word_edit', word_id=card.id) }}">редактировать</span></a>
                    <a class="btn btn-primary" href="{{ url_for('delete_word', word_id=card.id) }}">удалить</span></a>
                </div>
            </div>
            {% endfor %}
    </div>
    <div class="col-8">

    </div>
</div>
{% endblock %}